apiVersion: v1
kind: Service
metadata:
  name: zzzz
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 7860
    protocol: TCP
    name: web
  selector:
    app: zzzz
  type: LoadBalancer
  loadBalancerIP: 192.168.31.197
