apiVersion: apps/v1
kind: Deployment
metadata:
  name: zzzz
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: zzzz
  template:
    metadata:
      labels:
        app: zzzz
    spec:
      containers:
      - image: luminoussg/yolo-detection:v1
        name: zzzz
        ports:
        - containerPort: 7860
          name: web
        - containerPort: 8080
          name: web-alt
        - containerPort: 1935
          name: srt-tcp
          protocol: TCP
        - containerPort: 1935
          name: srt-udp
          protocol: UDP
        - containerPort: 4200
          name: srt-alt
          protocol: UDP 
