apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-deployment.yaml
  - app-svc.yaml

namespace: default

commonLabels:
  app.kubernetes.io/name: zzzz
  app.kubernetes.io/instance: zzzz

images:
  - name: luminoussg/yolo-detection:v1
    newTag: v1
