# Application configuration
app:
  name: yolo-detection
  image:
    repository: luminoussg/yolo-detection
    tag: v1
    pullPolicy: IfNotPresent
  
  # Resource limits and requests
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Git repository configuration for ArgoCD
gitRepo:
  url: "https://github.com/luminous0219/yolo-detection-k8s.git"  # Set this to your actual Git repository URL
  branch: "main"  # Set this to your desired branch

# Replica count and autoscaling configuration
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Service configuration
service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: "192.168.31.197"

# Pod configurations
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {} 