# This is a direct ArgoCD Application manifest (not a template)
# Use this file if you want to directly apply the application to ArgoCD without using Helm templates

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yolo-detection
  namespace: argocd
spec:
  project: default
  source:
    # IMPORTANT: Replace this with your actual Git repository URL
    repoURL: https://github.com/luminous0219/yolo-detection-k8s.git
    targetRevision: main
    path: prod
    helm:
      # You can provide value overrides here if needed
      values: |
        service:
          loadBalancerIP: "192.168.31.197"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# To apply this file:
# kubectl apply -f yolo-detection-argocd-app.yaml 
