apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.app.name }}
  namespace: argocd
spec:
  project: default
  source:
    # Replace with your actual Git repository URL
    repoURL: {{ .Values.gitRepo.url | default "https://github.com/yourusername/yolo-detection.git" }}
    targetRevision: {{ .Values.gitRepo.branch | default "main" }}
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 