apiVersion: v1
kind: Service
metadata:
  name: yolo-detection
  labels:
    app: yolo-detection
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7860
    protocol: TCP
    name: http
  selector:
    app: yolo-detection 